analyzer:
  exclude:
    - build/**
    - lib/**/*.g.dart

linter:
  rules:
    lines_longer_than_80_chars: false
    prefer_relative_imports: false
    prefer_collection_literals: false
    unnecessary_final: false
    avoid_annotating_with_dynamic: false
    sort_constructors_first: false
    avoid_types_on_closure_parameters: false
    avoid_as: false
    prefer_final_locals: false
    omit_local_variable_types: false
    prefer_double_quotes: false
    prefer_single_quotes: true
    use_key_in_widget_constructors: true
    prefer_spread_collections: true
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true
    unnecessary_await_in_return: true
    avoid_void_async: true
    unawaited_futures: true
    overridden_fields: true
    annotate_overrides: true
    parameter_assignments: true
    always_require_non_null_named_parameters: true
    prefer_final_in_for_each: true
    prefer_final_fields: true
    void_checks: true
    comment_references: true
    unrelated_type_equality_checks: true
    cascade_invocations: true
    diagnostic_describe_all_properties: false
    sort_child_properties_last: true
    join_return_with_assignment: true
    prefer_asserts_with_message: true
    prefer_null_aware_operators: true
    avoid_single_cascade_in_expression_statements: true
    unnecessary_parenthesis: true