name: tire_manager
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_svg: ^1.0.3
  hive_flutter: ^1.1.0
  hive: ^2.2.1
  hive_generator: ^1.1.3
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.11

flutter:

  uses-material-design: true

  assets:
    - assets/
